import numpy as np
import matplotlib.pyplot as plt


def read_gnu_datafile(
    filepath: str,
    efermi_offset: float = None,
    debug: bool = False,
):
    # Create docstring
    """
    Read a datafile generated by the GNUPlot script for bandstructure plotting.
    The datafile is expected to have the following format:
        - The first column is the k-point value
        - The second column is the energy value

    Parameters
    ----------
    filepath : str
        Path to the datafile
    efermi_offset : float, optional
        Value to offset the energy values by. Default is None.
    debug : bool, optional
        Whether to print debug messages. Default is False.

    Returns
    -------
    data : np.ndarray
        Array of shape (n_kpoints, n_bands, 2) where n_kpoints is the number of
        k-points and n_bands is the number of bands.
    """

    # Load data
    data = np.loadtxt(filepath)
    if debug:
        print("Loaded data with shape: ", data.shape)

    # Properly reshape
    unique_k, unique_k_count = np.unique(data[:, 0], return_counts=True)
    n_kpoints = unique_k_count[0]  # Count of the first k-point (0.000)
    data = data.reshape(n_kpoints, -1, 2)
    if debug:
        print("Reshaped data with shape: ", data.shape)

    return data


if __name__ == "__main__":
    d = read_gnu_datafile("../test/test_data/bandstructure_np/si_bands.dat.gnu")
    fig, ax = plt.subplots()
    for i in range(d.shape[0]):
        ax.plot(d[i, :, 0], d[i, :, 1], "k-", linewidth=1)
    plt.show()
